name: Deploy to VM

on:
  workflow_dispatch:
    inputs:
      images:
        description: 'image to push'
        required: true
        type: choice
        options:
          - vireo
          - vireo-dev
        default: 'vireo-dev'
      environment:
        description: 'stage(02) or prod(03)'
        required: true
        type: environment
        default: 'stage'

jobs:
  deploy:
    runs-on: [self-hosted]
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4

      - name: executing rsync as jhu-devops using secret
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: /
          remote_path: /opt/vireo/Vireo
          remote_host: ${{ secrets.VIREO_HOSTNAME }}
          remote_user: jhu-devops
          remote_key: ${{ secrets.JHU_DEVOPS_KEY }}

      - name: executing remote ssh commands as jhu-devops using secret
        uses: appleboy/ssh-action@v1
        env:
          PGPASSWORD: ${{ secrets.DB_PASSWORD}}
          # PGPASSWORD: vireo
          AUTH_SECURITY_JWT_SECRET: ${{ secrets.VIREO_JWT }}
          APP_SECURITY_SECRET: ${{ secrets.AUTH_CRYPTOSERVICE }}

        with:
          host: ${{ secrets.VIREO_HOSTNAME }}
          username: jhu-devops
          key: ${{ secrets.JHU_DEVOPS_KEY }}
          envs: PGPASSWORD, AUTH_SECURITY_JWT_SECRET, APP_SECURITY_SECRET
          script: |
            cd /opt/vireo/Vireo
            # docker compose down
            cp ../.env .env
            cp ../application.yml ./src/main/resources/application.yml
            cp vireo.service /etc/systemd/system/
            # Download WAR from GitHub Packages
            mkdir -p target
            curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -L https://maven.pkg.github.com/jhu-sheridan-libraries/vireo/org/tdl/vireo/4.2.10/vireo-4.2.10.war \
                 -o target/vireo-4.2.10.war
            # sudo chown -R vireo:vireo /opt/vireo/Vireo
            docker pull ghcr.io/jhu-sheridan-libraries/${{ inputs.images }}:4.2.10
            # docker compose up --detach
            # wget https://truststore.pki.rds.amazonaws.com/us-east-1/us-east-1-bundle.pem
            # sudo mv ./us-east-1-bundle.pem /etc/pki/ca-trust/source/
            # sudo update-ca-trust