name: RDS Clean Import

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'stage(02) or prod(03)'
        required: true
        type: environment
        default: 'prod'

jobs:
  deploy:
    runs-on: [self-hosted]
    environment: ${{ inputs.environment }}

    steps:
      - name: executing remote ssh command psql as jhu-devops using secrets
        uses: appleboy/ssh-action@v1
        env:
          PGPASSWORD: ${{ secrets.DB_PASSWORD}}
        with:
          host: msel-vireo02.mse.jhu.edu
          username: jhu-devops
          key: ${{ secrets.JHU_DEVOPS_KEY }}
          envs: PGPASSWORD
          script: |
            # Clean database before import
            /usr/bin/psql --host=${{ secrets.DB_HOST }} --port=5432 --dbname=vireo4 --username=${{ secrets.DB_USER }} -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;"
            # Import data
            /usr/bin/psql --host=${{ secrets.DB_HOST }} --port=5432 --dbname=vireo4 --username=${{ secrets.DB_USER }} < /opt/vireo/vireo4.dump
